// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.iw.ucajobs.domain;

import es.iw.ucajobs.domain.Titulo;
import es.iw.ucajobs.domain.TituloDataOnDemand;
import es.iw.ucajobs.domain.TituloIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TituloIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TituloIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TituloIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TituloIntegrationTest: @Transactional;
    
    @Autowired
    TituloDataOnDemand TituloIntegrationTest.dod;
    
    @Test
    public void TituloIntegrationTest.testCountTituloes() {
        Assert.assertNotNull("Data on demand for 'Titulo' failed to initialize correctly", dod.getRandomTitulo());
        long count = Titulo.countTituloes();
        Assert.assertTrue("Counter for 'Titulo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TituloIntegrationTest.testFindTitulo() {
        Titulo obj = dod.getRandomTitulo();
        Assert.assertNotNull("Data on demand for 'Titulo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Titulo' failed to provide an identifier", id);
        obj = Titulo.findTitulo(id);
        Assert.assertNotNull("Find method for 'Titulo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Titulo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TituloIntegrationTest.testFindAllTituloes() {
        Assert.assertNotNull("Data on demand for 'Titulo' failed to initialize correctly", dod.getRandomTitulo());
        long count = Titulo.countTituloes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Titulo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Titulo> result = Titulo.findAllTituloes();
        Assert.assertNotNull("Find all method for 'Titulo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Titulo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TituloIntegrationTest.testFindTituloEntries() {
        Assert.assertNotNull("Data on demand for 'Titulo' failed to initialize correctly", dod.getRandomTitulo());
        long count = Titulo.countTituloes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Titulo> result = Titulo.findTituloEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Titulo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Titulo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TituloIntegrationTest.testFlush() {
        Titulo obj = dod.getRandomTitulo();
        Assert.assertNotNull("Data on demand for 'Titulo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Titulo' failed to provide an identifier", id);
        obj = Titulo.findTitulo(id);
        Assert.assertNotNull("Find method for 'Titulo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTitulo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Titulo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TituloIntegrationTest.testMergeUpdate() {
        Titulo obj = dod.getRandomTitulo();
        Assert.assertNotNull("Data on demand for 'Titulo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Titulo' failed to provide an identifier", id);
        obj = Titulo.findTitulo(id);
        boolean modified =  dod.modifyTitulo(obj);
        Integer currentVersion = obj.getVersion();
        Titulo merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Titulo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TituloIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Titulo' failed to initialize correctly", dod.getRandomTitulo());
        Titulo obj = dod.getNewTransientTitulo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Titulo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Titulo' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Titulo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TituloIntegrationTest.testRemove() {
        Titulo obj = dod.getRandomTitulo();
        Assert.assertNotNull("Data on demand for 'Titulo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Titulo' failed to provide an identifier", id);
        obj = Titulo.findTitulo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Titulo' with identifier '" + id + "'", Titulo.findTitulo(id));
    }
    
}
