// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.iw.ucajobs.domain;

import es.iw.ucajobs.domain.Roles;
import es.iw.ucajobs.domain.RolesDataOnDemand;
import es.iw.ucajobs.domain.Users;
import es.iw.ucajobs.domain.UsersDataOnDemand;
import es.iw.ucajobs.reference.Sexo;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect UsersDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UsersDataOnDemand: @Component;
    
    private Random UsersDataOnDemand.rnd = new SecureRandom();
    
    private List<Users> UsersDataOnDemand.data;
    
    @Autowired
    RolesDataOnDemand UsersDataOnDemand.rolesDataOnDemand;
    
    public Users UsersDataOnDemand.getNewTransientUsers(int index) {
        Users obj = new Users();
        setActivado(obj, index);
        setApellidos(obj, index);
        setDni(obj, index);
        setEmail(obj, index);
        setFechaRegistro(obj, index);
        setNombre(obj, index);
        setPassword(obj, index);
        setRol(obj, index);
        setSexo(obj, index);
        setUsuario(obj, index);
        return obj;
    }
    
    public void UsersDataOnDemand.setActivado(Users obj, int index) {
        Boolean activado = true;
        obj.setActivado(activado);
    }
    
    public void UsersDataOnDemand.setApellidos(Users obj, int index) {
        String apellidos = "apellidos_" + index;
        obj.setApellidos(apellidos);
    }
    
    public void UsersDataOnDemand.setDni(Users obj, int index) {
        String dni = "dnixxx_" + index;
        obj.setDni(dni);
    }
    
    public void UsersDataOnDemand.setEmail(Users obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    public void UsersDataOnDemand.setFechaRegistro(Users obj, int index) {
        Date fechaRegistro = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaRegistro(fechaRegistro);
    }
    
    public void UsersDataOnDemand.setNombre(Users obj, int index) {
        String nombre = "nombre_" + index;
        obj.setNombre(nombre);
    }
    
    public void UsersDataOnDemand.setPassword(Users obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public void UsersDataOnDemand.setRol(Users obj, int index) {
        Roles rol = rolesDataOnDemand.getRandomRoles();
        obj.setRol(rol);
    }
    
    public void UsersDataOnDemand.setSexo(Users obj, int index) {
        Sexo sexo = Sexo.class.getEnumConstants()[0];
        obj.setSexo(sexo);
    }
    
    public void UsersDataOnDemand.setUsuario(Users obj, int index) {
        String usuario = "usuario_" + index;
        obj.setUsuario(usuario);
    }
    
    public Users UsersDataOnDemand.getSpecificUsers(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Users obj = data.get(index);
        Long id = obj.getId();
        return Users.findUsers(id);
    }
    
    public Users UsersDataOnDemand.getRandomUsers() {
        init();
        Users obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Users.findUsers(id);
    }
    
    public boolean UsersDataOnDemand.modifyUsers(Users obj) {
        return false;
    }
    
    public void UsersDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Users.findUsersEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Users' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Users>();
        for (int i = 0; i < 10; i++) {
            Users obj = getNewTransientUsers(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
