// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.iw.ucajobs.domain;

import es.iw.ucajobs.domain.Roles;

privileged aspect Roles_Roo_JavaBean {
    
    public String Roles.getNombre() {
        return this.nombre;
    }
    
    public void Roles.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
