// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.iw.ucajobs.domain;

import es.iw.ucajobs.domain.Trabajo;

privileged aspect Trabajo_Roo_JavaBean {
    
    public String Trabajo.getNombre() {
        return this.nombre;
    }
    
    public void Trabajo.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
