// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.iw.ucajobs.domain;

import es.iw.ucajobs.domain.Demandante;
import es.iw.ucajobs.domain.DemandanteDataOnDemand;
import es.iw.ucajobs.domain.UsersDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DemandanteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DemandanteDataOnDemand: @Component;
    
    private Random DemandanteDataOnDemand.rnd = new SecureRandom();
    
    private List<Demandante> DemandanteDataOnDemand.data;
    
    @Autowired
    UsersDataOnDemand DemandanteDataOnDemand.usersDataOnDemand;
    
    public Demandante DemandanteDataOnDemand.getNewTransientDemandante(int index) {
        Demandante obj = new Demandante();
        setPerfil(obj, index);
        return obj;
    }
    
    public void DemandanteDataOnDemand.setPerfil(Demandante obj, int index) {
        Demandante perfil = obj;
        obj.setPerfil(perfil);
    }
    
    public Demandante DemandanteDataOnDemand.getSpecificDemandante(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Demandante obj = data.get(index);
        Long id = obj.getId();
        return Demandante.findDemandante(id);
    }
    
    public Demandante DemandanteDataOnDemand.getRandomDemandante() {
        init();
        Demandante obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Demandante.findDemandante(id);
    }
    
    public boolean DemandanteDataOnDemand.modifyDemandante(Demandante obj) {
        return false;
    }
    
    public void DemandanteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Demandante.findDemandanteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Demandante' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Demandante>();
        for (int i = 0; i < 10; i++) {
            Demandante obj = getNewTransientDemandante(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
