// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.iw.ucajobs.domain;

import es.iw.ucajobs.domain.OfertaTrabajo;
import es.iw.ucajobs.domain.OfertaTrabajoDataOnDemand;
import es.iw.ucajobs.domain.OfertaTrabajoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OfertaTrabajoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OfertaTrabajoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OfertaTrabajoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OfertaTrabajoIntegrationTest: @Transactional;
    
    @Autowired
    OfertaTrabajoDataOnDemand OfertaTrabajoIntegrationTest.dod;
    
    @Test
    public void OfertaTrabajoIntegrationTest.testCountOfertaTrabajoes() {
        Assert.assertNotNull("Data on demand for 'OfertaTrabajo' failed to initialize correctly", dod.getRandomOfertaTrabajo());
        long count = OfertaTrabajo.countOfertaTrabajoes();
        Assert.assertTrue("Counter for 'OfertaTrabajo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OfertaTrabajoIntegrationTest.testFindOfertaTrabajo() {
        OfertaTrabajo obj = dod.getRandomOfertaTrabajo();
        Assert.assertNotNull("Data on demand for 'OfertaTrabajo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OfertaTrabajo' failed to provide an identifier", id);
        obj = OfertaTrabajo.findOfertaTrabajo(id);
        Assert.assertNotNull("Find method for 'OfertaTrabajo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'OfertaTrabajo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OfertaTrabajoIntegrationTest.testFindAllOfertaTrabajoes() {
        Assert.assertNotNull("Data on demand for 'OfertaTrabajo' failed to initialize correctly", dod.getRandomOfertaTrabajo());
        long count = OfertaTrabajo.countOfertaTrabajoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'OfertaTrabajo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<OfertaTrabajo> result = OfertaTrabajo.findAllOfertaTrabajoes();
        Assert.assertNotNull("Find all method for 'OfertaTrabajo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'OfertaTrabajo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OfertaTrabajoIntegrationTest.testFindOfertaTrabajoEntries() {
        Assert.assertNotNull("Data on demand for 'OfertaTrabajo' failed to initialize correctly", dod.getRandomOfertaTrabajo());
        long count = OfertaTrabajo.countOfertaTrabajoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<OfertaTrabajo> result = OfertaTrabajo.findOfertaTrabajoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'OfertaTrabajo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'OfertaTrabajo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OfertaTrabajoIntegrationTest.testFlush() {
        OfertaTrabajo obj = dod.getRandomOfertaTrabajo();
        Assert.assertNotNull("Data on demand for 'OfertaTrabajo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OfertaTrabajo' failed to provide an identifier", id);
        obj = OfertaTrabajo.findOfertaTrabajo(id);
        Assert.assertNotNull("Find method for 'OfertaTrabajo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOfertaTrabajo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'OfertaTrabajo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OfertaTrabajoIntegrationTest.testMergeUpdate() {
        OfertaTrabajo obj = dod.getRandomOfertaTrabajo();
        Assert.assertNotNull("Data on demand for 'OfertaTrabajo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OfertaTrabajo' failed to provide an identifier", id);
        obj = OfertaTrabajo.findOfertaTrabajo(id);
        boolean modified =  dod.modifyOfertaTrabajo(obj);
        Integer currentVersion = obj.getVersion();
        OfertaTrabajo merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'OfertaTrabajo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OfertaTrabajoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'OfertaTrabajo' failed to initialize correctly", dod.getRandomOfertaTrabajo());
        OfertaTrabajo obj = dod.getNewTransientOfertaTrabajo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'OfertaTrabajo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'OfertaTrabajo' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'OfertaTrabajo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OfertaTrabajoIntegrationTest.testRemove() {
        OfertaTrabajo obj = dod.getRandomOfertaTrabajo();
        Assert.assertNotNull("Data on demand for 'OfertaTrabajo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OfertaTrabajo' failed to provide an identifier", id);
        obj = OfertaTrabajo.findOfertaTrabajo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'OfertaTrabajo' with identifier '" + id + "'", OfertaTrabajo.findOfertaTrabajo(id));
    }
    
}
