// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.iw.ucajobs.domain;

import es.iw.ucajobs.domain.TituloIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TituloIntegrationTest_Roo_Configurable {
    
    declare @type: TituloIntegrationTest: @Configurable;
    
}
