// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.iw.ucajobs.domain;

import es.iw.ucajobs.domain.Trabajo;
import es.iw.ucajobs.domain.TrabajoDataOnDemand;
import es.iw.ucajobs.domain.TrabajoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TrabajoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TrabajoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TrabajoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TrabajoIntegrationTest: @Transactional;
    
    @Autowired
    TrabajoDataOnDemand TrabajoIntegrationTest.dod;
    
    @Test
    public void TrabajoIntegrationTest.testCountTrabajoes() {
        Assert.assertNotNull("Data on demand for 'Trabajo' failed to initialize correctly", dod.getRandomTrabajo());
        long count = Trabajo.countTrabajoes();
        Assert.assertTrue("Counter for 'Trabajo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TrabajoIntegrationTest.testFindTrabajo() {
        Trabajo obj = dod.getRandomTrabajo();
        Assert.assertNotNull("Data on demand for 'Trabajo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Trabajo' failed to provide an identifier", id);
        obj = Trabajo.findTrabajo(id);
        Assert.assertNotNull("Find method for 'Trabajo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Trabajo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TrabajoIntegrationTest.testFindAllTrabajoes() {
        Assert.assertNotNull("Data on demand for 'Trabajo' failed to initialize correctly", dod.getRandomTrabajo());
        long count = Trabajo.countTrabajoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Trabajo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Trabajo> result = Trabajo.findAllTrabajoes();
        Assert.assertNotNull("Find all method for 'Trabajo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Trabajo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TrabajoIntegrationTest.testFindTrabajoEntries() {
        Assert.assertNotNull("Data on demand for 'Trabajo' failed to initialize correctly", dod.getRandomTrabajo());
        long count = Trabajo.countTrabajoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Trabajo> result = Trabajo.findTrabajoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Trabajo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Trabajo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TrabajoIntegrationTest.testFlush() {
        Trabajo obj = dod.getRandomTrabajo();
        Assert.assertNotNull("Data on demand for 'Trabajo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Trabajo' failed to provide an identifier", id);
        obj = Trabajo.findTrabajo(id);
        Assert.assertNotNull("Find method for 'Trabajo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTrabajo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Trabajo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TrabajoIntegrationTest.testMergeUpdate() {
        Trabajo obj = dod.getRandomTrabajo();
        Assert.assertNotNull("Data on demand for 'Trabajo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Trabajo' failed to provide an identifier", id);
        obj = Trabajo.findTrabajo(id);
        boolean modified =  dod.modifyTrabajo(obj);
        Integer currentVersion = obj.getVersion();
        Trabajo merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Trabajo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TrabajoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Trabajo' failed to initialize correctly", dod.getRandomTrabajo());
        Trabajo obj = dod.getNewTransientTrabajo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Trabajo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Trabajo' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Trabajo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TrabajoIntegrationTest.testRemove() {
        Trabajo obj = dod.getRandomTrabajo();
        Assert.assertNotNull("Data on demand for 'Trabajo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Trabajo' failed to provide an identifier", id);
        obj = Trabajo.findTrabajo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Trabajo' with identifier '" + id + "'", Trabajo.findTrabajo(id));
    }
    
}
